#################################################################
#                                                               #
#                          Automations                          #
#                                                               #
#################################################################

- action:
  - service: script.1523505263098
  alias: Playroom Fan Level 1
  condition: []
  id: '1523506259174'
  trigger:
  - entity_id: input_select.playroom_fan
    platform: state
    to: Level 1
- action:
  - service: script.1523505294052
  alias: Playroom Fan Level 2
  condition: []
  id: '1523506309171'
  trigger:
  - entity_id: input_select.playroom_fan
    platform: state
    to: Level 2
- action:
  - service: script.1523505324933
  alias: Playroom Fan Level 3
  condition: []
  id: '1523506362068'
  trigger:
  - entity_id: input_select.playroom_fan
    platform: state
    to: Level 3
- action:
  - service: script.1523505358220
  alias: Playroom Fan Level 4
  condition: []
  id: '1523506407302'
  trigger:
  - entity_id: input_select.playroom_fan
    platform: state
    to: Level 4
- action:
  - service: script.1524684263950
  alias: Playroom Fan Oscillation On
  condition: []
  id: '1524684408949'
  trigger:
  - entity_id: input_select.playroom_fan_oscillate
    platform: state
    to: 'On'
- action:
  - service: script.1524684295834
  alias: Playroom Fan Oscillation Off
  condition: []
  id: '1524684465276'
  trigger:
  - entity_id: input_select.playroom_fan_oscillate
    platform: state
    to: 'Off'
- action:
  - service: script.1524684610404
  alias: Playroom Fan Left
  condition: []
  id: '1524684755156'
  trigger:
  - entity_id: input_select.playroom_fan_direction
    platform: state
    to: Left
- action:
  - service: script.1524684637559
  alias: Playroom Fan Right
  condition: []
  id: '1524684794880'
  trigger:
  - entity_id: input_select.playroom_fan_direction
    platform: state
    to: Right
- action:
  - service: script.1524685492627
  alias: Playroom Fan Angle 30°
  condition: []
  id: '1524685692186'
  trigger:
  - entity_id: input_select.playroom_fan_oscillation_angle
    platform: state
    to: 30°
- action:
  - service: script.1524685531855
  alias: Playroom Fan Angle 60°
  condition: []
  id: '1524685738008'
  trigger:
  - entity_id: input_select.playroom_fan_oscillation_angle
    platform: state
    to: 60°
- action:
  - service: script.1524685564893
  alias: Playroom Fan Angle 90°
  condition: []
  id: '1524685781740'
  trigger:
  - entity_id: input_select.playroom_fan_oscillation_angle
    platform: state
    to: 90°
- action:
  - service: script.1524685607962
  alias: Playroom Fan Angle 120°
  condition: []
  id: '1524685824683'
  trigger:
  - entity_id: input_select.playroom_fan_oscillation_angle
    platform: state
    to: 120°
- action:
  - service: script.1524685935022
  alias: Playroom Fan Natural Mode On
  condition: []
  id: '1524686015510'
  trigger:
  - entity_id: input_select.playroom_fan_natural_mode
    platform: state
    to: 'On'
- action:
  - service: script.1524685962145
  alias: Playroom Fan Natural Mode Off
  condition: []
  id: '1524686061379'
  trigger:
  - entity_id: input_select.playroom_fan_natural_mode
    platform: state
    to: 'Off'
- action:
  - service: script.1524686151270
  alias: Playroom Fan LED 0
  condition: []
  id: '1524686270827'
  trigger:
  - entity_id: input_select.playroom_fan_led_brightness
    platform: state
    to: '0'
- action:
  - service: script.1524686188825
  alias: Playroom Fan LED 1
  condition: []
  id: '1524686315547'
  trigger:
  - entity_id: input_select.playroom_fan_led_brightness
    platform: state
    to: '1'
- action:
  - service: script.1524686216404
  alias: Playroom Fan LED 2
  condition: []
  id: '1524686360333'
  trigger:
  - entity_id: input_select.playroom_fan_led_brightness
    platform: state
    to: '2'