#################################################################
#                                                               #
#                            Scripts                            #
#                                                               #
#################################################################

'1521694771100':
  alias: Evening TV
  sequence:
  - data:
      entity_id: switch.media_tv_power
    service: switch.turn_on
  - delay: 00:00:02
  - data:
      entity_id: switch.media_tv_select
    service: switch.turn_on
'1521695976118':
  alias: Morning Cartoons
  sequence:
  - data:
      entity_id: switch.media_tv_power
    service: switch.turn_on
  - delay: 00:00:20
  - data:
      entity_id: switch.media_tv_source
    service: switch.turn_on
  - data:
      entity_id: switch.media_tv_down
    service: switch.turn_on
  - data:
      entity_id: switch.media_tv_right
    service: switch.turn_on
  - data:
      entity_id: switch.media_tv_right
    service: switch.turn_on
  - data:
      entity_id: switch.media_tv_select
    service: switch.turn_on
  - delay: 00:00:15
  - data:
      entity_id: switch.media_tv_blue
    service: switch.turn_on
  - delay: 00:00:06
  - data:
      entity_id: switch.media_tv_7
    service: switch.turn_on
  - data:
      entity_id: switch.media_tv_0
    service: switch.turn_on
  - data:
      entity_id: switch.media_tv_3
    service: switch.turn_on
'1521696758169':
  alias: Super Rugby
  sequence:
  - data:
      entity_id: switch.media_tv_power
    service: switch.turn_on
  - delay: 00:00:03
  - data:
      entity_id: switch.media_tv_source
    service: switch.turn_on
  - data:
      entity_id: switch.media_tv_down
    service: switch.turn_on
  - data:
      entity_id: switch.media_tv_right
    service: switch.turn_on
  - data:
      entity_id: switch.media_tv_right
    service: switch.turn_on
  - data:
      entity_id: switch.media_tv_select
    service: switch.turn_on
  - delay: 00:00:15
  - data:
      entity_id: switch.media_tv_blue
    service: switch.turn_on
  - data:
      entity_id: switch.media_tv_5
    service: switch.turn_on
  - data:
      entity_id: switch.media_tv_0
    service: switch.turn_on
  - data:
      entity_id: switch.media_tv_5
    service: switch.turn_on
'1521697053706':
  alias: Watch Kodi
  sequence:
  - data:
      entity_id: switch.media_tv_power
    service: switch.turn_on
'1523505263098':
  alias: Playroom Fan Level 1
  sequence:
  - data:
      entity_id: fan.xiaomi_smart_fan
      speed: Level 1
    service: fan.set_speed
'1523505294052':
  alias: Playroom Fan Level 2
  sequence:
  - data:
      entity_id: fan.xiaomi_smart_fan
      speed: Level 2
    service: fan.set_speed
'1523505324933':
  alias: Playroom Fan Level 3
  sequence:
  - data:
      entity_id: fan.xiaomi_smart_fan
      speed: Level 3
    service: fan.set_speed
'1523505358220':
  alias: Playroom Fan Level 4
  sequence:
  - data:
      entity_id: fan.xiaomi_smart_fan
      speed: Level 4
    service: fan.set_speed
'1523649643350':
  alias: Turn On Fairy Lights
  sequence:
  - data:
      entity_id: switch.fairy_light_power
    service: switch.turn_on
  - data:
      entity_id: switch.fairy_light_mode_8
    service: switch.turn_on
'1524684263950':
  alias: Playroom Fan Oscillate On
  sequence:
  - data:
      entity_id: fan.xiaomi_smart_fan
      oscillating: 'true'
    service: fan.oscillate
'1524684295834':
  alias: Playroom Fan Oscillate Off
  sequence:
  - data:
      entity_id: fan.xiaomi_smart_fan
      oscillating: 'false'
    service: fan.oscillate
'1524684610404':
  alias: Playroom Fan Left
  sequence:
  - data:
      direction: left
      entity_id: fan.xiaomi_smart_fan
    service: fan.set_direction
'1524684637559':
  alias: Playroom Fan Right
  sequence:
  - data:
      direction: right
      entity_id: fan.xiaomi_smart_fan
    service: fan.set_direction
'1524685492627':
  alias: Playroom Fan Angle 30째
  sequence:
  - data:
      angle: '30'
      entity_id: fan.xiaomi_smart_fan
    service: fan.xiaomi_miio_set_oscillation_angle
'1524685531855':
  alias: Playroom Fan Angle 60째
  sequence:
  - data:
      angle: '60'
      entity_id: fan.xiaomi_smart_fan
    service: fan.xiaomi_miio_set_oscillation_angle
'1524685564893':
  alias: Playroom Fan Angle 90째
  sequence:
  - data:
      angle: '90'
      entity_id: fan.xiaomi_smart_fan
    service: fan.xiaomi_miio_set_oscillation_angle
'1524685607962':
  alias: Playroom Fan Angle 120째
  sequence:
  - data:
      angle: '120'
      entity_id: fan.xiaomi_smart_fan
    service: fan.xiaomi_miio_set_oscillation_angle
'1524685935022':
  alias: Playroom Fan Natural Mode On
  sequence:
  - data:
      entity_id: fan.xiaomi_smart_fan
    service: fan.xiaomi_miio_set_natural_mode_on
'1524685962145':
  alias: Playroom Fan Natural Mode Off
  sequence:
  - data:
      entity_id: fan.xiaomi_smart_fan
    service: fan.xiaomi_miio_set_natural_mode_off
'1524686151270':
  alias: Playroom Fan LED 0
  sequence:
  - data:
      brightness: '0'
      entity_id: fan.xiaomi_smart_fan
    service: fan.xiaomi_miio_set_led_brightness
'1524686188825':
  alias: Playroom Fan LED 1
  sequence:
  - data:
      brightness: '1'
      entity_id: fan.xiaomi_smart_fan
    service: fan.xiaomi_miio_set_led_brightness
'1524686216404':
  alias: Playroom Fan LED 2
  sequence:
  - data:
      brightness: '2'
      entity_id: fan.xiaomi_smart_fan
    service: fan.xiaomi_miio_set_led_brightness
