#################################################################
#                                                               #
#           Home Assistant Main Configuration File              #
#                                                               #
#################################################################

homeassistant:
  name: !secret name
  temperature_unit: C
  time_zone: !secret timezone
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  elevation: 6
  customize: !include includes/customize.yaml
  packages: !include_dir_named packages
  whitelist_external_dirs:
    - /config

#################################################################
#                                                               #
#                        Customizations                         #
#                                                               #
#################################################################

#customizer:
#  custom_ui: local
  
frontend:
  javascript_version: latest
  extra_html_url:
    - /local/custom_ui/fontawesome/hass-fontawesome-solid.html
    - /local/custom_ui/fontawesome/hass-fontawesome-regular.html
    - /local/custom_ui/fontawesome/hass-fontawesome-brands.html
    
lovelace:
  mode: yaml

custom_updater:
  show_installable: false
  hide_sensor: false
  track:
    - components
    - cards
    - python_scripts
  component_urls:
    - https://raw.githubusercontent.com/keatontaylor/custom_components/master/custom_components.json
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
    - https://raw.githubusercontent.com/maykar/custom-lovelace/master/tracker.json
    - https://raw.githubusercontent.com/ljmerza/waze-card/master/updater.json
    - https://raw.githubusercontent.com/iammexx/home-assistant-config/master/ui/darksky/version.json
    
#################################################################
#                                                               #
#                           Enables                             #
#                                                               #
#################################################################

config:

hassio:

api:
  api_password: !secret api_password

http:
  api_password: !secret http_password

updater:
    
conversation:

history:

logbook:

map:

discovery:
  ignore:
    - yeelight
    
####################################################
#                                                  #
#                    Includes                      #
#                                                  #
####################################################

python_script: !include_dir_named python_scripts
script: !include includes/scripts.yaml
switch: !include includes/switches.yaml
zone: !include includes/zones.yaml

####################################################
#                                                  #
#                      Logger                      #
#                                                  #
####################################################

logger:
  default: error
  
####################################################
#                                                  #
#                      MQTT                        #
#                                                  #
####################################################

mqtt: 
  broker: !secret broker
  port: !secret broker_port
  username: !secret broker_user
  password: !secret broker_pass
  
#################################################################
#                                                               #
#                            Panel                              #
#                                                               #
#################################################################

panel_iframe:
  ide:
    title: IDE
    icon: mdi:code-braces
    url: !secret ide_url
  nodered:
    title: Node-RED
    icon: mdi:sitemap
    url: !secret node_red_url
  sonweb:
    title: SonWEB
    icon: mdi:lightbulb-on
    url: !secret sonweb_url

####################################################
#                                                  #
#                     Recorder                     #
#                                                  #
####################################################

recorder:
  purge_interval: 1
  purge_keep_days: 14
