#################################################################
#                                                               #
#                   Packages/Climate Control                    #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:
## Downstairs Climate Control
    sensor.temperature_158d0001f558f5:
      friendly_name: Downstairs Temperature
    sensor.humidity_158d0001f558f5:
      friendly_name: Downstairs Humidity 
    sensor.illumination_158d0001e5d118:
      friendly_name: Downstairs LUX
    input_select.lounge_aircon:
      icon: mdi:snowflake
    input_select.lounge_fan:
      icon: mdi:fan 
    binary_sensor.switch_158d000201ce4e:
      friendly_name: Lounge Fan Switch  
    climate.downstairs_climate:
      icon: mdi:snowflake
    climate.upstairs_climate:
      icon: mdi:snowflake
      
## Upstairs Climate Control
    sensor.temperature_158d0001f53de9:
      friendly_name: Bedroom Temperature
    sensor.humidity_158d0001f53de9:
      friendly_name: Bedroom Humidity 
    sensor.illumination_158d0001e63803:
      friendly_name: Bedroom LUX
    input_select.master_bedroom_aircon:
      icon: mdi:snowflake
    input_select.bedroom_fan:
      icon: mdi:fan 
    binary_sensor.switch_158d000233a19d:
      friendly_name: Bedside Fan Switch
    binary_sensor.switch_158d000215aa27:
      friendly_name: Bedroom Wall Fan Switch
      
## Playroom Climate Control
    sensor.temperature_158d0001f56682:
      friendly_name: Playroom Temperature
    sensor.humidity_158d0001f56682:
      friendly_name: Playroom Humidity  
    sensor.illumination_158d0001e5cf11:
      friendly_name: Playroom LUX
      
    sensor.lower_temperature:
      friendly_name: Downstairs Temperature
      icon: mdi:sofa
    sensor.upstairs_temperature:
      icon: mdi:hotel
      
#################################################################
#                                                               #
#                           Group                               #
#                                                               #
#################################################################

group:
## Downstairs Climate Control
  climate control:
    name: Climate Control
    view: no
    entities:
      - sensor.temperature_158d0001f558f5
      - sensor.humidity_158d0001f558f5
      - sensor.illumination_158d0001e5d118
      - input_select.lounge_aircon
      - input_select.lounge_fan
      - climate.downstairs_climate
      
## Upstairs Climate Control
  master bedroom climate:
    name: Master Bedroom Climate
    view: no
    entities:
      - sensor.temperature_158d0001f53de9
      - sensor.humidity_158d0001f53de9
      - sensor.illumination_158d0001e63803
      - input_select.master_bedroom_aircon
      - input_select.bedroom_fan
      - climate.upstairs_climate
      
## Playroom Climate Control
  play room climate:
    name: Play Room Climate
    view: no
    entities:
      - sensor.temperature_158d0001f56682
      - sensor.humidity_158d0001f56682
      - sensor.illumination_158d0001e5cf11
      - fan.xiaomi_smart_fan
      #- input_select.playroom_fan

#################################################################
#                                                               #
#                             Fan                               #
#                                                               #
#################################################################

fan:

####################################################
#                                                  #
#                    Fan - MQTT                    #
#                                                  #
####################################################

### Bedroom Fan ###
  - platform: mqtt  
    name: "Bedroom Fan"
    command_topic: "cmnd/bedroom_fan/FanSpeed"
    speed_command_topic: "cmnd/bedroom_fan/FanSpeed"    
    state_topic: "stat/bedroom_fan/RESULT"
    speed_state_topic: "stat/bedroom_fan/RESULT"
    state_value_template: >
      {% if value_json.FanSpeed is defined %}
        {% if value_json.FanSpeed == 0 -%}0{%- elif value_json.FanSpeed > 0 -%}4{%- endif %}
      {% else %}
        {% if states.fan.bedroom_fan.state == 'off' -%}0{%- elif states.fan.bedroom_fan.state == 'on' -%}4{%- endif %}
      {% endif %}
    speed_value_template: "{{ value_json.FanSpeed }}"
    availability_topic: tele/bedroom_fan/LWT
    payload_off: "0"
    payload_on: "4"
    payload_low_speed: "1"
    payload_medium_speed: "2"
    payload_high_speed: "3"
    payload_available: Online
    payload_not_available: Offline
    speeds:
      - off
      - low
      - medium
      - high

### Lounge Fan ###
  - platform: mqtt  
    name: "Lounge Fan"
    command_topic: "cmnd/lounge_fan/FanSpeed"
    speed_command_topic: "cmnd/lounge_fan/FanSpeed"    
    state_topic: "stat/lounge_fan/RESULT"
    speed_state_topic: "stat/lounge_fan/RESULT"
    state_value_template: >
      {% if value_json.FanSpeed is defined %}
        {% if value_json.FanSpeed == 0 -%}0{%- elif value_json.FanSpeed > 0 -%}4{%- endif %}
      {% else %}
        {% if states.fan.lounge_fan.state == 'off' -%}0{%- elif states.fan.lounge_fan.state == 'on' -%}4{%- endif %}
      {% endif %}
    speed_value_template: "{{ value_json.FanSpeed }}"
    availability_topic: tele/lounge_fan/LWT
    payload_off: "0"
    payload_on: "4"
    payload_low_speed: "1"
    payload_medium_speed: "2"
    payload_high_speed: "3"
    payload_available: Online
    payload_not_available: Offline
    speeds:
      - off
      - low
      - medium
      - high
      
### Jackson Fan ###
  - platform: mqtt  
    name: "Jackson Fan"
    command_topic: "cmnd/jackson-fan/FanSpeed"
    speed_command_topic: "cmnd/jackson-fan/FanSpeed"    
    state_topic: "stat/jackson-fan/RESULT"
    speed_state_topic: "stat/jackson-fan/RESULT"
    state_value_template: >
      {% if value_json.FanSpeed is defined %}
        {% if value_json.FanSpeed == 0 -%}0{%- elif value_json.FanSpeed > 0 -%}4{%- endif %}
      {% else %}
        {% if states.fan.jackson_fan.state == 'off' -%}0{%- elif states.fan.jackson_fan.state == 'on' -%}4{%- endif %}
      {% endif %}
    speed_value_template: "{{ value_json.FanSpeed }}"
    availability_topic: tele/jackson-fan/LWT
    payload_off: "0"
    payload_on: "4"
    payload_low_speed: "1"
    payload_medium_speed: "2"
    payload_high_speed: "3"
    payload_available: Online
    payload_not_available: Offline
    speeds:
      - off
      - low
      - medium
      - high
      
### Hudson Fan ###
  - platform: mqtt  
    name: "Hudson Fan"
    command_topic: "cmnd/hudson-fan/FanSpeed"
    speed_command_topic: "cmnd/hudson-fan/FanSpeed"    
    state_topic: "stat/hudson-fan/RESULT"
    speed_state_topic: "stat/hudson-fan/RESULT"
    state_value_template: >
      {% if value_json.FanSpeed is defined %}
        {% if value_json.FanSpeed == 0 -%}0{%- elif value_json.FanSpeed > 0 -%}4{%- endif %}
      {% else %}
        {% if states.fan.hudson_fan.state == 'off' -%}0{%- elif states.fan.hudson_fan.state == 'on' -%}4{%- endif %}
      {% endif %}
    speed_value_template: "{{ value_json.FanSpeed }}"
    availability_topic: tele/hudson-fan/LWT
    payload_off: "0"
    payload_on: "4"
    payload_low_speed: "1"
    payload_medium_speed: "2"
    payload_high_speed: "3"
    payload_available: Online
    payload_not_available: Offline
    speeds:
      - off
      - low
      - medium
      - high

####################################################
#                                                  #
#                   Fan - Xiaomi                   #
#                                                  #
####################################################

  - platform: xiaomi_miio_fan
    name: Xiaomi Smart Fan
    host: !secret xiaomi_fan_ip
    token: !secret xiaomi_fan_token
    
#################################################################
#                                                               #
#                           Inputs                              #
#                                                               #
#################################################################

input_select:
## Downstairs Air Conditioner
  lounge_aircon:
    name: Lounge Climate
    options:
      - Climate Off
      - Cool
      - Heat
    initial: Climate Off
    #icon: mdi:snowflake
    
## Lounge Fan  
  lounge_fan:
    name: Lounge Fan 
    options:
      - Fan Off
      - Low 
      - Medium
      - High
    initial: Fan Off
    #icon: mdi:fan
    
## Master Bedroom Air Conditioner
  master_bedroom_aircon:
    name: Master Bedroom Climate
    options:
      - Climate Off
      - Cool
      - Heat
    initial: Climate Off
    #icon: mdi:snowflake

## Master Bedroom Fan    
  bedroom_fan:
    name: Bedroom Fan 
    options:
      - Fan Off
      - Low 
      - Medium
      - High
    initial:  Fan Off
    #icon: mdi:fan 
    
## Jackson Bedroom Fan    
  jackson_fan:
    name: Jackson Fan 
    options:
      - Fan Off
      - Low 
      - Medium
      - High
    initial:  Fan Off
    
## Hudson Bedroom Fan    
  hudson_fan:
    name: Hudson Fan 
    options:
      - Fan Off
      - Low 
      - Medium
      - High
    initial:  Fan Off
    
#################################################################
#                                                               #
#                            Scenes                             #
#                                                               #
#################################################################

scene:
## Downstairs Air Conditioner
  - name: "Climate Cool"
    entities:
      switch.aircon_mode_cool: on

  - name: "Climate Heat"
    entities:
      switch.aircon_mode_heat: on

  - name: "Climate Off"
    entities:
      switch.aircon_power: off
      
## Upstairs Air Conditioner - This Section needs to be fixed before summer ir codes are incorrect
  - name: "Bedroom Climate Mode"
    entities:
      switch.bedroom_aircon_mode: on

  - name: "Bedroom Climate Off"
    entities:
      switch.bedroom_aircon_power: off

  - name: "Bedroom Climate On"
    entities:
      switch.bedroom_aircon_power: on
      
#################################################################
#                                                               #
#                           Sensors                             #
#                                                               #
#################################################################

sensor:

####################################################
#                                                  #
#                Sensors - Min/Max                 #
#                                                  #
####################################################

  - platform: min_max
    name: "Lower Temperature"
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.temperature_158d0001f558f5
      - sensor.temperature_158d0001f56682
      
  - platform: min_max
    name: "Upstairs Temperature"
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.temperature_158d0001f534e1
      - sensor.temperature_158d0001f53de9
      - sensor.temperature_158d0001f54df3
      - sensor.temperature_158d00022c7248
      
####################################################
#                                                  #
#                  Sensors - MQTT                  #
#                                                  #
####################################################

  - platform: mqtt
    name: "Lounge Fan Switch"
    state_topic: "downstairs_fan"
    
  - platform: mqtt
    name: "Bedroom Fan Switch"
    state_topic: "bedroom_fan"
    
  - platform: mqtt
    name: "Jackson Fan Switch"
    state_topic: "jackson_fan"
    
  - platform: mqtt
    name: "Hudson Fan Switch"
    state_topic: "hudson_fan"

####################################################
#                                                  #
#                Sensors - Template                #
#                                                  #
####################################################

  - platform: template
    sensors:
      playroom_fan_speed:
        friendly_name: "Speed"
        value_template: "{{ states.fan.xiaomi_smart_fan.attributes.speed }}"
        
      playroom_fan_oscillate:
        friendly_name: "Oscillate"
        value_template: "{{ states.fan.xiaomi_smart_fan.attributes.oscillate }}"
        
      playroom_fan_speed_level:
        friendly_name: "Speed Level"
        value_template: "{{ states.fan.xiaomi_smart_fan.attributes.speed_level }}"
        
      playroom_fan_angle:
        friendly_name: "Angle"
        value_template: "{{ states.fan.xiaomi_smart_fan.attributes.angle }}"
        unit_of_measurement: "°"
        
      playroom_fan_power:
        friendly_name: "Power"
        value_template: "{{ states.fan.xiaomi_smart_fan.attributes.ac_power }}"
        
      playroom_fan_temperature:
        friendly_name: "Temperature"
        value_template: "{{ states.fan.xiaomi_smart_fan.attributes.temperature }}"
        unit_of_measurement: "°"
        
      playroom_fan_humidity:
        friendly_name: "Humidity"
        value_template: "{{ states.fan.xiaomi_smart_fan.attributes.humidity }}"
        unit_of_measurement: "%"
        
      playroom_fan_battery:
        friendly_name: "Battery"
        value_template: "{{ states.fan.xiaomi_smart_fan.attributes.battery }}"
        unit_of_measurement: "%"
        device_class: battery
        icon_template: >-
          {% if is_state('sensor.playroom_fan_battery_charge', 'progress') and is_state('sensor.playroom_fan_power', 'True') %}
            mdi:battery-charging
          {% elif is_state('sensor.playroom_fan_battery_charge', 'complete') and is_state('sensor.playroom_fan_power', 'True') %}
            mdi:power-plug
          {% endif %}
        
      playroom_fan_battery_charge:
        friendly_name: "Battery Charge"
        value_template: "{{ states.fan.xiaomi_smart_fan.attributes.battery_charge }}"
        device_class: battery
    

#################################################################
#                                                               #
#                         Automations                           #
#                                                               #
#################################################################

## All automations for this package have now been moved to Node-RED please see Node-Red Flows folder within this package for more infomation! ##

automation:
